name: BUILD CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: kt-sejnipwd
          POSTGRES_DB: kt-sejni
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 11
            distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' && github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2  
      - name: Build
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_APP_EMAIL}}

  DOCKER:
    needs: [ CD ]
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' && github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Docker Build and Push
            uses: docker/build-push-action@v2.7.0
            with:
              context: .
              file: Dockerfile
              push: true
              tags: |
                ${{ secrets.DOCKER_USERNAME }}/sejni:latest
                ${{ secrets.DOCKER_USERNAME }}/sejni:v${{ github.run_number }}

  NOTIFICATION:
    needs: [ DOCKER ]
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' && github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_MESSAGE: 'Yeahhhhhh!!! :sunglasses:'
          SLACK_TITLE: Message
          SLACK_USERNAME: gitHub-Sejni
